# Generated by Django 4.2.7 on 2025-06-08 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_document', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_number', models.AutoField(primary_key=True, serialize=False)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_points', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.AutoField(primary_key=True, serialize=False)),
                ('PNR_number', models.CharField(max_length=20, unique=True)),
                ('ticketing_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('checkin_status', models.BooleanField(default=False)),
                ('seat_number', models.CharField(max_length=5)),
                ('gate_number', models.CharField(max_length=5)),
                ('class_type', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business')], max_length=10)),
                ('carry_on', models.BooleanField(default=True)),
                ('baggage', models.IntegerField(default=0)),
                ('extra_baggage', models.IntegerField(default=0)),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.flightinstance')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.passenger')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='accounts.payment')),
            ],
        ),
    ]
