# Generated by Django 4.2.7 on 2025-06-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
    ]
