# Generated by Django 4.2.7 on 2025-06-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20250617_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
