# Generated by Django 4.2.7 on 2025-06-17 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0003_delete_ticket'),
        ('ticket', '0003_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PNR_number', models.CharField(max_length=20)),
                ('checkin_status', models.CharField(choices=[('not_checked_in', 'Not Checked In'), ('checked_in', 'Checked In'), ('boarded', 'Boarded')], default='not_checked_in', max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('extra_baggage', models.BooleanField(default=False)),
                ('ticketing_timestamp', models.DateTimeField(auto_now_add=True)),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flightclass')),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flightinstance')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.passenger')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='flights.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
