# Generated by Django 4.2.7 on 2025-06-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
    ]
