# Generated by Django 4.2.7 on 2025-06-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_delete_ticket'),
        ('ticket', '0005_remove_ticket_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='flights.payment'),
        ),
    ]
