# Generated by Django 4.2.7 on 2025-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('id_document', models.TextField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('area_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passenger_id', models.CharField(max_length=20, unique=True)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
