# Generated by Django 4.2.7 on 2025-06-11 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.AutoField(primary_key=True, serialize=False)),
                ('register', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('seats_business', models.IntegerField()),
                ('seats_economy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_area_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountMultiplier',
            fields=[
                ('discount_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('discount_coefficient', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('fnum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('class_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('baggage', models.IntegerField()),
                ('carry_on', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gate_number', models.CharField(max_length=10)),
                ('price_base_multiplier', models.DecimalField(decimal_places=4, max_digits=5)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_instances', to='flights.aircraft')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='flights.flight')),
            ],
            options={
                'unique_together': {('flight', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_document', models.CharField(max_length=50)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('area_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens', to='flights.country')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.discountmultiplier')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_number', models.AutoField(primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FrequentTraveler',
            fields=[
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flights.passenger')),
                ('FQTV_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flights.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('PNR_number', models.CharField(max_length=10)),
                ('checkin_status', models.CharField(choices=[('not_checked_in', 'Not Checked In'), ('checked_in', 'Checked In'), ('boarded', 'Boarded')], default='not_checked_in', max_length=20)),
                ('seat_number', models.CharField(max_length=5)),
                ('extra_baggage', models.IntegerField(default=0)),
                ('ticketing_timestamp', models.DateTimeField(auto_now_add=True)),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flightclass')),
                ('flight_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flightinstance')),
                ('passengers', models.ManyToManyField(related_name='tickets', to='flights.passenger')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='flights.payment')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='flights.country')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='flights.city'),
        ),
        migrations.CreateModel(
            name='CaregiverInfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infants', to='flights.passenger')),
                ('infant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='flights.passenger')),
            ],
            options={
                'unique_together': {('caregiver', 'infant')},
            },
        ),
    ]
