# Generated by Django 4.2.7 on 2025-06-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_ticket_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
